# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e4fc0abddf73e59057bb048e765e5f976c2f6a6f9a348d3089e2ad28f9d629a38203f8c2a83dd96a815083eee77952f8e9c71d163786210697a9b47899a32cbb

test:
  secret_key_base: 7b1e2282fe437fc14d56dd4e2973cc04504f5cf6b4c446cebe688b4b3619b1742a316c6ae68d978beffcf42416fc19789479d17b52b443fa8a5bcaea85792ec1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
